### ISSUE TITLE
[BUG] Mods cannot be disabled even enable is set to false

### ISSUE THREAD

**Issue by KrisCris** [soulsmods/ModEngine2#57] opened 2022-06-02 06:35 UTC
```toml
mods = [
    { enabled = false, name = "EldenRingRandomizer", path = "randomizer" }
]
```

This won't work. The only way to disable mods is commenting out this line.

**Comment by garyttierney** [comment] 2022-06-02 10:43
Duplicate of #41

**Closed by garyttierney** 2022-06-02 10:43 UTC
